package com.comm.model;

import java.util.Date;

import javax.ws.rs.FormParam;

import com.comm.util.BaseForm;

public class TbRecruitApplicantProfile extends BaseForm {
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column tb_recruit_applicant_profile.ID
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	@FormParam("id")
	private Long id;

	@FormParam("ownerCustomerId")
	private Long ownerCustomerId;

	@FormParam("marriageStatus")
	private Integer marriageStatus;
	
	@FormParam("yearOfAttend")
	private Integer yearOfAttend;
	
	@FormParam("isUnifyAdmission")
	private Integer isUnifyAdmission;
	
	@FormParam("jobSeekStatus")
	private Integer jobSeekStatus;
	
	
	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column tb_recruit_applicant_profile.high_education
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	@FormParam("highEducation")
	private String highEducation;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column tb_recruit_applicant_profile.industry
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	@FormParam("industry")
	private String industry;
	
	@FormParam("industryId")
	private String industryId;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column tb_recruit_applicant_profile.last_company
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	@FormParam("lastCompany")
	private String lastCompany;

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column tb_recruit_applicant_profile.last_position
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	@FormParam("lastPosition")
	private String lastPosition;
	@FormParam("lastPositionId")
	private String lastPositionId;

	public String getIndustryId() {
		return industryId;
	}

	public void setIndustryId(String industryId) {
		this.industryId = industryId;
	}

	public String getLastPositionId() {
		return lastPositionId;
	}

	public void setLastPositionId(String lastPositionId) {
		this.lastPositionId = lastPositionId;
	}

	/**
	 * This field was generated by Abator for iBATIS. This field corresponds to
	 * the database column tb_recruit_applicant_profile.is_valid
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	/*@FormParam("isValid")
	private String isValid;

	private TbCommCustomer tbCommCustomer;

	public TbCommCustomer getTbCommCustomer() {
		return tbCommCustomer;
	}

	public void setTbCommCustomer(TbCommCustomer tbCommCustomer) {
		this.tbCommCustomer = tbCommCustomer;
	}
*/
	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column tb_recruit_applicant_profile.ID
	 * 
	 * @return the value of tb_recruit_applicant_profile.ID
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public Long getId() {
		return id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column tb_recruit_applicant_profile.ID
	 * 
	 * @param id
	 *            the value for tb_recruit_applicant_profile.ID
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public void setId(Long id) {
		this.id = id;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column tb_recruit_applicant_profile.nick_name
	 * 
	 * @return the value of tb_recruit_applicant_profile.nick_name
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column tb_recruit_applicant_profile.high_education
	 * 
	 * @return the value of tb_recruit_applicant_profile.high_education
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public String getHighEducation() {
		return highEducation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column tb_recruit_applicant_profile.high_education
	 * 
	 * @param highEducation
	 *            the value for tb_recruit_applicant_profile.high_education
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public void setHighEducation(String highEducation) {
		this.highEducation = highEducation;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column tb_recruit_applicant_profile.industry
	 * 
	 * @return the value of tb_recruit_applicant_profile.industry
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public String getIndustry() {
		return industry;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column tb_recruit_applicant_profile.industry
	 * 
	 * @param industry
	 *            the value for tb_recruit_applicant_profile.industry
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public void setIndustry(String industry) {
		this.industry = industry;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column tb_recruit_applicant_profile.last_company
	 * 
	 * @return the value of tb_recruit_applicant_profile.last_company
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public String getLastCompany() {
		return lastCompany;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column tb_recruit_applicant_profile.last_company
	 * 
	 * @param lastCompany
	 *            the value for tb_recruit_applicant_profile.last_company
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public void setLastCompany(String lastCompany) {
		this.lastCompany = lastCompany;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column tb_recruit_applicant_profile.last_position
	 * 
	 * @return the value of tb_recruit_applicant_profile.last_position
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public String getLastPosition() {
		return lastPosition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column tb_recruit_applicant_profile.last_position
	 * 
	 * @param lastPosition
	 *            the value for tb_recruit_applicant_profile.last_position
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
	public void setLastPosition(String lastPosition) {
		this.lastPosition = lastPosition;
	}

	/**
	 * This method was generated by Abator for iBATIS. This method returns the
	 * value of the database column tb_recruit_applicant_profile.is_valid
	 * 
	 * @return the value of tb_recruit_applicant_profile.is_valid
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 */
/*	public String getIsValid() {
		return isValid;
	}

	*//**
	 * This method was generated by Abator for iBATIS. This method sets the
	 * value of the database column tb_recruit_applicant_profile.is_valid
	 * 
	 * @param isValid
	 *            the value for tb_recruit_applicant_profile.is_valid
	 * 
	 * @abatorgenerated Fri May 03 08:20:11 CST 2013
	 *//*
	public void setIsValid(String isValid) {
		this.isValid = isValid;
	}*/

	public Long getOwnerCustomerId() {
		return ownerCustomerId;
	}

	public void setOwnerCustomerId(Long ownerCustomerId) {
		this.ownerCustomerId = ownerCustomerId;
	}

	public Integer getMarriageStatus() {
		return marriageStatus;
	}

	public void setMarriageStatus(Integer marriageStatus) {
		this.marriageStatus = marriageStatus;
	}

	public Integer getYearOfAttend() {
		return yearOfAttend;
	}

	public void setYearOfAttend(Integer yearOfAttend) {
		this.yearOfAttend = yearOfAttend;
	}

	public Integer getIsUnifyAdmission() {
		return isUnifyAdmission;
	}

	public void setIsUnifyAdmission(Integer isUnifyAdmission) {
		this.isUnifyAdmission = isUnifyAdmission;
	}

	public Integer getJobSeekStatus() {
		return jobSeekStatus;
	}

	public void setJobSeekStatus(Integer jobSeekStatus) {
		this.jobSeekStatus = jobSeekStatus;
	}

	
	
	
	
	
}